web:
  build: .
  command: php -S 0.0.0.0:8080 -t /prestashop
  ports:
    - "8080:8080"
  links:
    - db
  volumes:
    - .:/prestashop
db:
  image: partlab/ubuntu-mariadb
  environment:
    MARIADB_DATABASE: prestashop
